### ISSUE TITLE
Acknowledge text not appearing

### ISSUE THREAD

**Issue by reginfo** [zbxwallboard/ZbxWallboard#1]
Hi,

When I try to acknowledge a problem with some text it`s not appearing.
![capture](https://user-images.githubusercontent.com/4628571/46998470-4a96dd00-d12b-11e8-9489-473f82038233.JPG)

**Comment by mjaepel** [comment]
Which Zabbix Version do you use?
Seems to be related to the known issue with acks on Zabbix >= 4.0.

I prepared it for 4.0, so it sends an api param that doesn't exists in < 4.0.

**Comment by reginfo** [comment]
I`m using Zabbix 4.0.0.

**Comment by mjaepel** [comment]
Fixed in 8fcf7341c53931e0b98c582f41506a00a71142ca

There was only the wrong action used. All known acknowledge issues with Zabbix 4.0 solved by this change.
I am unsure what happens with Versions < 4.0 now. I will test it later.

**Comment by mjaepel** [comment]
Compatibility for version < 4.0 added in e264003fde487f920e4b830412d4c23dfe14cfe1
All done. :)

**Comment by reginfo** [comment]
Thanks! It works!
