### ISSUE TITLE
Hide Maintenance

### ISSUE THREAD

**Issue by ghost** [zbxwallboard/ZbxWallboard#6]
Is it posable to make the button hide maintenance avalable just as the stand alone version has?
I realy like this option. 

great work with this plugin bdw :P

**Comment by mjaepel** [comment]
Maybe you should take a look into the filter options? The filter form is based on the official problem overview. I removed only some options that aren't needed for the wallboard.
But option "show suppressed problems" is still there. Uncheck this and you will see only problems without active maintenances.

**Comment by ghost** [comment]
![20200612_221307](https://user-images.githubusercontent.com/51781072/84542803-7a302b00-acfa-11ea-8889-7645779f8d6f.jpg)

This is how it looks for me.
if i uncheck it it still shows them.
and when i check it it also shows them.

**Comment by mjaepel** [comment]
Ah I see. I used also the code for the view of the official problems as base and removed some code that's not needed in this case. It seems that I removed too much. :(

**Comment by mjaepel** [comment]
Fixed :)

**Comment by ghost** [comment]
Thank u for fixing this so fast!
I think u should put the new zbxwallboard in zabbix contribution program to be official supported by zabbix.
Because they did not use your other feature request :P
