### ISSUE TITLE
Error Code 11

### ISSUE THREAD

**Issue by Ycshell** [zbxwallboard/ZbxWallboard#8]
No active API login

'ZABBIX' => array(
		/* Full URL to Zabbix api. Includes api_jsonrpc.php! */
		'URL' => 'https://localhost/zabbix/api_jsonrpc.php',
		
		/* User which should be used for api connection */
		'USERNAME' => 'Admin',
		
		/* 
			Password for api user.
			Values:
				'string' - means used password
				null - no password used, only needed for unauth guest user
		*/
		'PASSWORD' => '123456',
		
		/* 
			Basic Auth is optional. Depends on your Zabbix installation.
			If activated we will do a double authentication:
				1) HTTP basic auth against webserver
				2) regular api auth against JSON RPC
			Same credentials for both.
			
			Values:
				0 - means disabled
				1 - means activated
		*/
		'BASIC_AUTH' => 1
	),

**Comment by mjaepel** [comment]
What do you want to say?

**Comment by Ycshell** [comment]
No active API login ,Error Code 11
How do you soive this ?

**Comment by mjaepel** [comment]
This error describes that the wallboard is unable to login at the zabbix api. There are many possible reasons ...

- wrong url
- wrong username / password
- firewall
- different username / password for basic auth and api
- ...

**Comment by mjaepel** [comment]
It could be helpful for other users with the same problem when you describe your solution. ;)
